---
#Install K8s on nodes
- hosts: k8s
  remote_user: aenglema
  roles:
    - ubuntu-k8s-install

#Set up K8s master
- hosts: k8s-master
  remote_user: aenglema
  gather_facts: true
  roles:
    - k8s-master

- hosts: k8s-workers
  remote_user: aenglema
  tasks: 
    - name: join cluster
      shell: "{{ hostvars['k8smaster'].join_command }} --ignore-preflight-errors all >> node_joined.txt"
      args: 
        chdir: $HOME
        creates: node_joined.txt

