---
- name: kubeadm init
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16 >> /root/kubadm-init.txt
  args:
    creates: "/root/kubeadm-init.txt"
  become: yes

- name: set up kubeadm for non-root
  file:
    path: "/home/{{ ansible_user_id }}/.kube"
    state: directory
    owner: "{{ ansible_user_id }}"
  
- name: copy kubectl admin.conf to user
  become: yes
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user_id }}/.kube/config"
    owner: "{{ ansible_user_id }}"

- name: kubectl apply
  shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml >> tigera-operator.txt
  args:
    chdir: $HOME
    creates: tigera-operator.txt

- shell: kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml >> custom-resources.txt
  args:
    chdir: $HOME
    creates: custom-resources.txt
